public  class Address {  //Assignment Week-2
    public void homeAddress(){

        String Name = 'Nalan';
        Integer totalMembers = 4;
        String houseName = 'Budak';
        integer houseNumber = 2700;
        String streetName = 'SugarLake';
        String cityName = 'SugarLand';
        String stateName = 'Texas';
        String stateIsoCode = 'TX';
        String countryName = 'United State Of America';
        String countryIsoCode= 'USA';
        Integer zipCode = 77479;
        Boolean isThisYourHomeOrNot = true;
        
        System.debug('My name is Nalan '+ name);
        System.debug('Number of members in my family '+ totalMembers);
        System.debug('Our house name '+ houseName);
        System.debug('Our house number '+ houseNumber);
        system.debug('Street name '+ streetName);
        System.debug('City name '+ cityName);
        system.debug('State ISO Code : ' + stateIsoCode );
        system.debug('Country Name '+ countryName);
        System.debug('Country ISO Code ' + countryIsoCode);
        system.debug('Zip Code ' + zipCode);
        System.debug('Is this your home or not? '+ isThisYourHomeOrNot);
        
        
            }
}
