public class CalculationHW {
    public Integer add(Integer a, Integer b) {
       Integer sum = a + b;
       return sum;

    }
    public integer subtract(integer n, Integer m){
        integer subtract = n - m;
        return subtract;
    }
    public Integer multiply(integer y, integer z){
        integer multiply =y * z;
        return multiply;
        
    }
    public integer divide(Integer k, integer l){
        Integer divide = k / l;
        return divide;
    }
}