public  class CaseTriggerHandler {   //10/23/2022  Assignment Week9
/*
    public static void checkForDescription(List<Case> triggerNew) {
      set<id> caseId = new Set<Id>();
        for (Case eachCase : triggerNew) {
            if (eachCase.Description.containsIgnoreCase('password')) {
                caseId.add(eachCase.Id);                                
            }            
        }
        if (!caseId.isEmpty()) {
            List<Case> caseList = new List<Case>();
            for (Id eachId : caseId) {
                case cs = new Case();
                cs.Subject = 'Parent Case may contain secret info, do something NOW';
                cs.ParentId = eachId;
                cs.Priority = 'High';
                cs.Description =  'Secret info not allowed in case';
                caseList.add(cs);
            }   
            insert caseList;
         
        }
    } */
}
