public class SOQL_Assinment_Day13 {
   public static void assignment(){
       

   }
}













/*1-Write an SOQL query using Average aggregate function from Account object 
on field  NumberOfEmployee.

2-Write an SOQL query using Average aggregate function from Account object 
on field  NumberOfEmployees and group them by Industry.

3-Write an SOQL query for contact Object querying Account object fields in the 
same query referring ID and Name and pass them to a list<Contact> 
lstcontact records.
--Run the above the over the for loop and display the account id and 
account name.

4-Write an SOQL query for Account Object querying contact object fields in the 
same query referring ID and Name and pass them to a list<Account> 
lstaccount records.
--Run the above the over the for loop and display the Contact id and 
Contact name.
*/
