Decimal calc = Calculator.dynamicCalulationMethod(10, 67.5,'ADDITION');
System.debug('ADDITION ===> '+ calc);

Decimal calc2 = Calculator.dynamicCalulationMethod(90, 60, 'SUBSTRACTION');
System.debug('SUBTRACTION ==> ' +calc2);


Decimal calc3 = Calculator.dynamicCalulationMethod(8, 2, 'DIVISION');
System.debug('DIVISION ===> ' + calc3);


Decimal calc4 = Calculator.dynamicCalulationMethod(6, 4, 'MULTIPLACATION');
System.debug('MULTIPLICATION ==> ' + calc4);