// week2- Assignment 

Planets earth = new Planets();
earth.planetName = 'Earth';
earth.planetNumber = 3;
earth.numberOfMoons = 1;

Planets neptune= new Planets();
neptune.planetName='Neptune';
neptune.planetNumber= 8;
neptune.numberOfMoons = 2;

System.debug(earth);
System.debug(neptune);


/*Create objects for Earth
  Create an object for your favorite non-earth planet.
And print the object values in the debug message.*/



